/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available strategies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of strategies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StrategyListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List strategy modules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Strategy modules */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StrategyModulesResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create or update a strategy module */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StrategyModulePayload"];
                };
            };
            responses: {
                /** @description Updated module */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StrategyModuleOperationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List providers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Providers response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProvidersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategy/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List strategy instances */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Instances response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstancesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StrategyConfig: {
            name: string;
            type: string;
            description: string;
            default?: unknown;
            required: boolean;
        };
        Strategy: {
            name: string;
            displayName: string;
            description: string;
            version?: string;
            config: components["schemas"]["StrategyConfig"][];
            events: string[];
        };
        StrategyListResponse: {
            strategies: components["schemas"]["Strategy"][];
        };
        StrategyDiagnostic: {
            stage?: string;
            message?: string;
            line?: number;
            column?: number;
            hint?: string;
        };
        StrategyModuleRevision: {
            hash: string;
            tag?: string;
            path: string;
            version?: string;
            size: number;
            retired?: boolean;
        };
        ModuleRunningSummary: {
            hash: string;
            instances: string[] | null;
            count: number;
            firstSeen?: string | null;
            lastSeen?: string | null;
            running?: boolean;
        };
        StrategyModuleResolution: {
            name: string;
            hash: string;
            tag?: string;
            version?: string;
            file?: string;
            path?: string;
        };
        StrategyModuleSummary: {
            name: string;
            file: string;
            path: string;
            hash: string;
            version?: string;
            tags: string[];
            tagAliases?: {
                [key: string]: string;
            };
            revisions?: components["schemas"]["StrategyModuleRevision"][];
            running?: components["schemas"]["ModuleRunningSummary"][] | null;
            size: number;
            metadata: components["schemas"]["Strategy"];
        };
        StrategyModulesResponse: {
            modules: components["schemas"]["StrategyModuleSummary"][];
            total?: number;
            offset?: number;
            limit?: number | null;
            strategyDirectory?: string;
        };
        StrategyModulePayload: {
            filename?: string;
            source: string;
            name?: string;
            tag?: string;
            aliases?: string[];
            promoteLatest?: boolean;
        };
        StrategyModuleOperationResponse: {
            filename?: string;
            status: string;
            strategyDirectory: string;
            module?: components["schemas"]["StrategyModuleResolution"] | null;
        };
        ProviderSettings: {
            [key: string]: unknown;
        };
        /** @enum {string} */
        ProviderStatus: "pending" | "starting" | "running" | "stopped" | "failed";
        Provider: {
            name: string;
            adapter: string;
            identifier: string;
            instrumentCount: number;
            settings: components["schemas"]["ProviderSettings"];
            running: boolean;
            status: components["schemas"]["ProviderStatus"];
            startupError?: string;
            dependentInstances?: string[] | null;
            dependentInstanceCount?: number | null;
        };
        Instrument: {
            symbol: string;
            type?: string;
            baseAsset?: string | null;
            baseCurrency?: string | null;
            quoteAsset?: string | null;
            quoteCurrency?: string | null;
            venue?: string | null;
            expiry?: string | null;
            contractValue?: number | null;
            contractCurrency?: string | null;
            strike?: number | null;
            optionType?: string | null;
            priceIncrement?: number | null;
            quantityIncrement?: number | null;
            pricePrecision?: number | null;
            quantityPrecision?: number | null;
            notionalPrecision?: number | null;
            minNotional?: number | null;
            minQuantity?: number | null;
            maxQuantity?: number | null;
        };
        SettingsSchema: {
            name: string;
            type: string;
            default?: unknown;
            description?: string | null;
            required: boolean;
        };
        AdapterMetadata: {
            identifier: string;
            displayName: string;
            venue: string;
            description?: string;
            capabilities: string[];
            settingsSchema: components["schemas"]["SettingsSchema"][];
        };
        ProviderDetail: {
            name: string;
            adapter: components["schemas"]["AdapterMetadata"];
            identifier: string;
            instrumentCount: number;
            settings: components["schemas"]["ProviderSettings"];
            running: boolean;
            status: components["schemas"]["ProviderStatus"];
            startupError?: string;
            dependentInstances?: string[] | null;
            dependentInstanceCount?: number | null;
            instruments: components["schemas"]["Instrument"][];
        };
        ProvidersResponse: {
            providers: components["schemas"]["Provider"][];
        };
        ProviderRequest: {
            name: string;
            adapter: {
                identifier: string;
                config: {
                    [key: string]: unknown;
                };
            };
            enabled?: boolean;
        };
        ProviderSymbols: {
            symbols: string[];
        };
        LambdaStrategySpec: {
            identifier: string;
            config: {
                [key: string]: unknown;
            };
            selector?: string;
            tag?: string;
            hash?: string;
            version?: string;
        };
        InstanceLinks: {
            self?: string;
            usage?: string;
        };
        ModuleRevisionUsage: {
            strategy: string;
            hash: string;
            instances: string[] | null;
            count: number;
            firstSeen?: string | null;
            lastSeen?: string | null;
            running?: boolean;
        };
        InstanceSummary: {
            id: string;
            strategyIdentifier: string;
            strategyTag?: string;
            strategyHash?: string;
            strategyVersion?: string;
            strategySelector?: string;
            providers: string[];
            aggregatedSymbols: string[];
            running: boolean;
            baseline?: boolean;
            dynamic?: boolean;
            createdAt?: string | null;
            updatedAt?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            usage?: components["schemas"]["ModuleRevisionUsage"];
            links?: components["schemas"]["InstanceLinks"];
        };
        InstanceSpec: {
            id: string;
            strategy: components["schemas"]["LambdaStrategySpec"];
            scope: {
                [key: string]: components["schemas"]["ProviderSymbols"];
            };
            providers?: string[];
            aggregatedSymbols?: string[];
            running?: boolean;
        };
        InstancesResponse: {
            instances: components["schemas"]["InstanceSummary"][];
        };
        ExecutionRecord: {
            orderId: string;
            provider: string;
            strategyInstance: string;
            executionId: string;
            quantity: string;
            price: string;
            fee?: string | null;
            feeAsset?: string | null;
            liquidity?: string | null;
            tradedAt: number;
            metadata?: {
                [key: string]: unknown;
            };
            createdAt: number;
        };
        ExecutionHistoryResponse: {
            executions: components["schemas"]["ExecutionRecord"][];
            count: number;
        };
        OrderRecord: {
            id: string;
            provider: string;
            strategyInstance: string;
            clientOrderId: string;
            symbol: string;
            side: string;
            type: string;
            quantity: string;
            price?: string | null;
            state: string;
            externalReference?: string | null;
            placedAt: number;
            metadata?: {
                [key: string]: unknown;
            };
            acknowledgedAt?: number | null;
            completedAt?: number | null;
            createdAt: number;
            updatedAt: number;
        };
        OrderHistoryResponse: {
            orders: components["schemas"]["OrderRecord"][];
            count: number;
        };
        BalanceRecord: {
            provider: string;
            asset: string;
            total: string;
            available: string;
            snapshotAt: number;
            metadata?: {
                [key: string]: unknown;
            };
            createdAt: number;
            updatedAt: number;
        };
        BalanceHistoryResponse: {
            balances: components["schemas"]["BalanceRecord"][];
            count: number;
        };
        CircuitBreakerConfig: {
            enabled: boolean;
            threshold: number;
            cooldown: string;
        };
        RiskConfig: {
            maxPositionSize: string;
            maxNotionalValue: string;
            notionalCurrency: string;
            orderThrottle: number;
            orderBurst: number;
            maxConcurrentOrders: number;
            priceBandPercent: number;
            allowedOrderTypes: string[];
            killSwitchEnabled: boolean;
            maxRiskBreaches: number;
            circuitBreaker: components["schemas"]["CircuitBreakerConfig"];
        };
        FanoutWorkersSetting: number | string;
        EventbusRuntimeConfig: {
            bufferSize: number;
            fanoutWorkers: components["schemas"]["FanoutWorkersSetting"];
        };
        ObjectPoolRuntimeConfig: {
            size: number;
            waitQueueSize: number;
        };
        PoolRuntimeConfig: {
            event: components["schemas"]["ObjectPoolRuntimeConfig"];
            orderRequest: components["schemas"]["ObjectPoolRuntimeConfig"];
        };
        ApiServerConfig: {
            addr: string;
        };
        TelemetryConfig: {
            otlpEndpoint: string;
            serviceName: string;
            otlpInsecure: boolean;
            enableMetrics: boolean;
        };
        RuntimeConfig: {
            eventbus: components["schemas"]["EventbusRuntimeConfig"];
            pools: components["schemas"]["PoolRuntimeConfig"];
            risk: components["schemas"]["RiskConfig"];
            apiServer: components["schemas"]["ApiServerConfig"];
            telemetry: components["schemas"]["TelemetryConfig"];
        };
        /** @enum {string} */
        RuntimeConfigSource: "runtime" | "file" | "bootstrap";
        RuntimeConfigSnapshot: {
            config: components["schemas"]["RuntimeConfig"];
            source: components["schemas"]["RuntimeConfigSource"];
            persistedAt?: string | null;
            filePath?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        ProviderRuntimeMetadata: {
            name: string;
            adapter: string;
            identifier: string;
            instrumentCount: number;
            settings?: {
                [key: string]: unknown;
            } | null;
            running: boolean;
            status: components["schemas"]["ProviderStatus"];
            startupError?: string;
        };
        LambdaInstanceSnapshot: {
            id: string;
            strategy: components["schemas"]["LambdaStrategySpec"];
            providers: string[];
            providerSymbols: {
                [key: string]: components["schemas"]["ProviderSymbols"];
            };
            aggregatedSymbols: string[];
            running: boolean;
            baseline?: boolean;
            dynamic?: boolean;
            createdAt?: string | null;
            updatedAt?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        ConfigBackup: {
            version: string;
            generatedAt: string;
            environment: string;
            meta: {
                name?: string;
                version?: string;
                description?: string;
            };
            runtime: components["schemas"]["RuntimeConfig"];
            providers: {
                config: {
                    [key: string]: {
                        [key: string]: unknown;
                    };
                } | null;
                runtime: components["schemas"]["ProviderRuntimeMetadata"][];
            };
            lambdas: {
                instances: components["schemas"]["LambdaInstanceSnapshot"][];
            };
        };
        RestoreConfigResponse: {
            status: string;
            providers: number;
            lambdas: number;
        };
        ContextBackupPayload: {
            providers: {
                [key: string]: unknown;
            }[];
            lambdas: components["schemas"]["InstanceSpec"][];
            risk: {
                [key: string]: unknown;
            };
        };
        RestoreContextResponse: {
            status: string;
        };
        StrategyRefreshRequest: {
            hashes?: string[];
            strategies?: string[];
        };
        StrategyRefreshResult: {
            selector: string;
            strategy?: string;
            hash?: string;
            previousHash?: string;
            instances?: string[];
            reason?: string;
        };
        StrategyRefreshResponse: {
            status: string;
            results?: components["schemas"]["StrategyRefreshResult"][];
        };
        StrategyModuleUsageResponse: {
            selector: string;
            strategy: string;
            hash: string;
            usage: components["schemas"]["ModuleRevisionUsage"];
            instances: components["schemas"]["InstanceSummary"][];
            total: number;
            offset: number;
            limit?: number | null;
        };
        StrategyRegistryLocation: {
            tag: string;
            path: string;
        };
        StrategyRegistryEntry: {
            tags: {
                [key: string]: string;
            };
            hashes: {
                [key: string]: components["schemas"]["StrategyRegistryLocation"];
            };
        };
        StrategyRegistryExport: {
            registry: {
                [key: string]: components["schemas"]["StrategyRegistryEntry"];
            };
            usage: components["schemas"]["ModuleRevisionUsage"][];
        };
        ApiErrorPayload: {
            status?: string;
            error: string;
            message?: string;
            diagnostics?: components["schemas"]["StrategyDiagnostic"][];
        };
        StrategyErrorResponse: components["schemas"]["ApiErrorPayload"];
        StrategyValidationErrorResponse: components["schemas"]["StrategyErrorResponse"] & {
            /** @constant */
            error: "strategy_validation_failed";
            message: string;
        };
        OutboxAggregateType: string;
        OutboxEvent: {
            id: number;
            aggregateType: components["schemas"]["OutboxAggregateType"];
            aggregateID: string;
            eventType: string;
            payload: {
                [key: string]: unknown;
            };
            headers: {
                [key: string]: unknown;
            };
            availableAt: string;
            publishedAt?: string | null;
            attempts: number;
            lastError?: string | null;
            delivered: boolean;
            createdAt: string;
        };
        OutboxListResponse: {
            events: components["schemas"]["OutboxEvent"][];
            count: number;
        };
        OutboxDeleteResponse: {
            id: number;
            status: string;
        };
        OutboxQuery: {
            limit?: number;
            delivered?: boolean;
            aggregateType?: string;
            aggregateID?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
