/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available strategies */
        get: operations["listStrategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a single strategy by identifier */
        get: operations["getStrategy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List JavaScript strategy modules available to the runtime */
        get: operations["listStrategyModules"];
        put?: never;
        /** Upload or register a new strategy module revision */
        post: operations["createStrategyModule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/modules/{selector}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Strategy name, name:tag, or name@hash identifying the module */
                selector: string;
            };
            cookie?: never;
        };
        /** Fetch metadata for a specific module selector */
        get: operations["getStrategyModule"];
        /** Update an existing module revision */
        put: operations["updateStrategyModule"];
        post?: never;
        /** Remove a module revision */
        delete: operations["deleteStrategyModule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/modules/{selector}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the raw JavaScript source for a module */
        get: operations["getStrategyModuleSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/modules/{selector}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect runtime usage for a module revision */
        get: operations["getStrategyModuleUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/modules/{name}/tags/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Strategy name */
                name: string;
                /** @description Tag alias to mutate */
                tag: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Reassign a tag alias to a different hash */
        put: operations["assignStrategyModuleTag"];
        post?: never;
        /** Remove a tag alias from the registry */
        delete: operations["deleteStrategyModuleTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reload strategies from disk, optionally targeting specific hashes */
        post: operations["refreshStrategies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export registry.json merged with live usage */
        get: operations["exportStrategyRegistry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provider runtimes */
        get: operations["listProviders"];
        put?: never;
        /** Create a provider */
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Fetch a provider */
        get: operations["getProvider"];
        /** Update a provider */
        put: operations["updateProvider"];
        post?: never;
        /** Remove a provider */
        delete: operations["deleteProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{name}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a provider asynchronously */
        post: operations["startProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a provider */
        post: operations["stopProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{name}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve provider balance snapshots */
        get: operations["listProviderBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered adapters */
        get: operations["listAdapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adapters/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve adapter metadata */
        get: operations["getAdapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategy/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List strategy instances */
        get: operations["listInstances"];
        put?: never;
        /** Create a strategy instance */
        post: operations["createInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategy/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Fetch an instance snapshot */
        get: operations["getInstance"];
        /** Update an instance */
        put: operations["updateInstance"];
        post?: never;
        /** Delete an instance */
        delete: operations["deleteInstance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategy/instances/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an instance */
        post: operations["startInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategy/instances/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop an instance */
        post: operations["stopInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategy/instances/{id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent orders for an instance */
        get: operations["listInstanceOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategy/instances/{id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent executions for an instance */
        get: operations["listInstanceExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve runtime risk limits */
        get: operations["getRiskLimits"];
        /** Apply runtime risk limits */
        put: operations["updateRiskLimits"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/context/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export providers, lambdas, and risk config */
        get: operations["exportContext"];
        put?: never;
        /** Restore providers, lambdas, and risk config from a backup */
        post: operations["restoreContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending outbox events */
        get: operations["listOutbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a pending outbox event */
        delete: operations["deleteOutbox"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StrategyConfig: {
            name: string;
            type: string;
            description?: string;
            default?: unknown;
            required: boolean;
        };
        Strategy: {
            name: string;
            displayName: string;
            description: string;
            tag?: string;
            config: components["schemas"]["StrategyConfig"][];
            events: string[];
        };
        StrategyListResponse: {
            strategies: components["schemas"]["Strategy"][];
        };
        StrategyModuleRevision: {
            hash: string;
            tag?: string;
            path: string;
            /** Format: int64 */
            size: number;
            retired?: boolean;
        };
        ModuleRunningSummary: {
            hash: string;
            instances?: string[] | null;
            count: number;
            /** Format: date-time */
            firstSeen?: string | null;
            /** Format: date-time */
            lastSeen?: string | null;
        };
        StrategyModuleSummary: {
            name: string;
            file: string;
            path: string;
            hash: string;
            tag?: string;
            tags: string[];
            tagAliases?: {
                [key: string]: string;
            };
            revisions?: components["schemas"]["StrategyModuleRevision"][];
            running?: components["schemas"]["ModuleRunningSummary"][];
            /** Format: int64 */
            size: number;
            metadata: components["schemas"]["Strategy"];
        };
        StrategyModulesResponse: {
            modules: components["schemas"]["StrategyModuleSummary"][];
            total?: number;
            offset?: number;
            limit?: number | null;
            strategyDirectory?: string;
        };
        StrategyModulePayload: {
            filename?: string;
            name?: string;
            tag?: string;
            aliases?: string[];
            reassignTags?: string[];
            promoteLatest?: boolean;
            source: string;
        };
        StrategyModuleResolution: {
            name?: string;
            hash?: string;
            tag?: string;
            alias?: string;
            file?: string;
            path?: string;
        };
        StrategyModuleOperationResponse: {
            filename?: string;
            status: string;
            strategyDirectory: string;
            module?: components["schemas"]["StrategyModuleResolution"];
        };
        StrategyTagAssignmentRequest: {
            hash: string;
            refresh?: boolean;
        };
        StrategyTagMutationResponse: {
            status: string;
            strategy: string;
            tag: string;
            hash?: string;
            previousHash?: string;
            allowOrphan?: boolean;
            refresh?: boolean;
        };
        StrategyRefreshRequest: {
            hashes?: string[];
            strategies?: string[];
        };
        StrategyRefreshResult: {
            selector: string;
            strategy?: string;
            hash?: string;
            previousHash?: string;
            instances?: string[];
            reason?: string;
        };
        StrategyRefreshResponse: {
            status: string;
            results?: components["schemas"]["StrategyRefreshResult"][];
        };
        ProviderSettings: {
            [key: string]: unknown;
        };
        /** @enum {string} */
        ProviderStatus: "pending" | "starting" | "running" | "stopped" | "failed";
        Provider: {
            name: string;
            adapter: string;
            identifier: string;
            instrumentCount: number;
            settings: components["schemas"]["ProviderSettings"];
            running: boolean;
            status: components["schemas"]["ProviderStatus"];
            startupError?: string;
            dependentInstances?: string[] | null;
            dependentInstanceCount?: number | null;
        };
        Instrument: {
            symbol?: string;
            type?: string;
            baseAsset?: string | null;
            baseCurrency?: string | null;
            quoteAsset?: string | null;
            quoteCurrency?: string | null;
            venue?: string | null;
            expiry?: string | null;
            contractValue?: number | null;
        };
        ProviderDetail: components["schemas"]["Provider"] & {
            instruments?: components["schemas"]["Instrument"][];
            adapter?: components["schemas"]["AdapterMetadata"];
        };
        ProvidersResponse: {
            providers: components["schemas"]["Provider"][];
        };
        ProviderRequest: {
            name: string;
            adapter: {
                identifier: string;
                config: {
                    [key: string]: unknown;
                };
            };
            enabled?: boolean;
        };
        ProviderSymbols: {
            symbols: string[];
        };
        AdapterMetadata: {
            identifier: string;
            displayName: string;
            venue: string;
            description?: string;
            capabilities: string[];
            settingsSchema: {
                name: string;
                type: string;
                default?: unknown;
                description?: string | null;
                required: boolean;
            }[];
        };
        AdaptersResponse: {
            adapters: components["schemas"]["AdapterMetadata"][];
        };
        LambdaStrategySpec: {
            identifier: string;
            selector?: string;
            tag?: string;
            hash?: string;
            config: {
                [key: string]: unknown;
            };
        };
        InstanceLinks: {
            self?: string;
            usage?: string;
        };
        ModuleRevisionUsage: {
            strategy: string;
            hash: string;
            instances?: string[] | null;
            count: number;
            /** Format: date-time */
            firstSeen?: string | null;
            /** Format: date-time */
            lastSeen?: string | null;
            running?: boolean;
        };
        InstanceSummary: {
            id: string;
            strategyIdentifier: string;
            strategyTag?: string;
            strategyHash?: string;
            strategySelector?: string;
            providers: string[];
            aggregatedSymbols: string[];
            running: boolean;
            baseline?: boolean;
            dynamic?: boolean;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            usage?: components["schemas"]["ModuleRevisionUsage"];
            links?: components["schemas"]["InstanceLinks"];
        };
        InstanceSpec: {
            id: string;
            strategy: components["schemas"]["LambdaStrategySpec"];
            scope: {
                [key: string]: components["schemas"]["ProviderSymbols"];
            };
            providers?: string[];
            aggregatedSymbols?: string[];
            running?: boolean;
        };
        InstancesResponse: {
            instances: components["schemas"]["InstanceSummary"][];
        };
        InstanceActionResponse: {
            id: string;
            status: string;
            /** @enum {string} */
            action: "start" | "stop";
        };
        OrderRecord: {
            id: string;
            provider: string;
            strategyInstance: string;
            clientOrderId: string;
            symbol: string;
            side: string;
            type: string;
            quantity: string;
            price?: string | null;
            state: string;
            externalReference?: string | null;
            placedAt: number;
            metadata?: {
                [key: string]: unknown;
            };
            acknowledgedAt?: number | null;
            completedAt?: number | null;
            createdAt: number;
            updatedAt: number;
        };
        OrderHistoryResponse: {
            orders: components["schemas"]["OrderRecord"][];
            count: number;
        };
        ExecutionRecord: {
            orderId: string;
            provider: string;
            strategyInstance: string;
            executionId: string;
            quantity: string;
            price: string;
            fee?: string | null;
            feeAsset?: string | null;
            liquidity?: string | null;
            tradedAt: number;
            metadata?: {
                [key: string]: unknown;
            };
            createdAt: number;
        };
        ExecutionHistoryResponse: {
            executions: components["schemas"]["ExecutionRecord"][];
            count: number;
        };
        BalanceRecord: {
            provider: string;
            asset: string;
            total: string;
            available: string;
            snapshotAt: number;
            metadata?: {
                [key: string]: unknown;
            };
            createdAt: number;
            updatedAt: number;
        };
        BalanceHistoryResponse: {
            balances: components["schemas"]["BalanceRecord"][];
            count: number;
        };
        StrategyModuleUsageResponse: {
            selector: string;
            strategy: string;
            hash: string;
            usage: components["schemas"]["ModuleRevisionUsage"];
            instances: components["schemas"]["InstanceSummary"][];
            total: number;
            offset: number;
            limit?: number | null;
        };
        StrategyRegistryExport: {
            registry: {
                [key: string]: {
                    tags: {
                        [key: string]: string;
                    };
                    hashes: {
                        [key: string]: {
                            tag: string;
                            path: string;
                        };
                    };
                };
            };
            usage: components["schemas"]["ModuleRevisionUsage"][];
        };
        RiskConfig: {
            maxPositionSize: string;
            maxNotionalValue: string;
            notionalCurrency: string;
            orderThrottle: number;
            orderBurst: number;
            maxConcurrentOrders: number;
            priceBandPercent: number;
            allowedOrderTypes: string[];
            killSwitchEnabled: boolean;
            maxRiskBreaches: number;
            circuitBreaker: {
                enabled: boolean;
                threshold: number;
                cooldown: string;
            };
        };
        ContextBackupPayload: {
            providers: {
                [key: string]: unknown;
            }[];
            lambdas: components["schemas"]["InstanceSpec"][];
            risk: components["schemas"]["RiskConfig"];
        };
        RestoreContextResponse: {
            status: string;
        };
        OutboxQuery: {
            limit?: number;
        };
        OutboxEvent: {
            id: number;
            aggregateType: string;
            aggregateID: string;
            eventType: string;
            payload: {
                [key: string]: unknown;
            };
            headers: {
                [key: string]: unknown;
            };
            availableAt: string;
            publishedAt?: string | null;
            attempts: number;
            lastError?: string | null;
            delivered: boolean;
            createdAt: string;
        };
        OutboxListResponse: {
            events: components["schemas"]["OutboxEvent"][];
            count: number;
        };
        OutboxDeleteResponse: {
            id: number;
            status: string;
        };
        ApiErrorPayload: {
            error: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorPayload"];
            };
        };
    };
    parameters: {
        InstanceId: string;
        ProviderName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listStrategies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strategy catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Canonical strategy identifier */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strategy metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    listStrategyModules: {
        parameters: {
            query?: {
                /** @description Filter by strategy identifier */
                strategy?: string;
                /** @description Filter by revision hash */
                hash?: string;
                /** @description When true, only return modules that currently power running instances */
                runningOnly?: boolean;
                /** @description Maximum number of modules to return */
                limit?: number;
                /** @description Offset into the filtered module set */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strategy module listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyModulesResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createStrategyModule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyModulePayload"];
            };
        };
        responses: {
            /** @description Module staged and awaiting refresh */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyModuleOperationResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getStrategyModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Strategy name, name:tag, or name@hash identifying the module */
                selector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyModuleSummary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateStrategyModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Strategy name, name:tag, or name@hash identifying the module */
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyModulePayload"];
            };
        };
        responses: {
            /** @description Module updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyModuleOperationResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteStrategyModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Strategy name, name:tag, or name@hash identifying the module */
                selector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getStrategyModuleSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module source contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/javascript": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getStrategyModuleUsage: {
        parameters: {
            query?: {
                /** @description Include dormant instances that still pin the revision */
                includeStopped?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage and instance summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyModuleUsageResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    assignStrategyModuleTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Strategy name */
                name: string;
                /** @description Tag alias to mutate */
                tag: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyTagAssignmentRequest"];
            };
        };
        responses: {
            /** @description Tag reassigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyTagMutationResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteStrategyModuleTag: {
        parameters: {
            query?: {
                /** @description Force removal even if this is the last alias referencing the hash */
                allowOrphan?: boolean;
            };
            header?: never;
            path: {
                /** @description Strategy name */
                name: string;
                /** @description Tag alias to mutate */
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyTagMutationResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshStrategies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StrategyRefreshRequest"];
            };
        };
        responses: {
            /** @description Refresh status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRefreshResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportStrategyRegistry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registry export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRegistryExport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderRequest"];
            };
        };
        responses: {
            /** @description Provider accepted for creation */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderRequest"];
            };
        };
        responses: {
            /** @description Provider updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        name?: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider start requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    stopProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ProviderName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProviderBalances: {
        parameters: {
            query?: {
                /** @description Maximum number of balances to return */
                limit?: number;
                /** @description Filter by asset ticker */
                asset?: string;
            };
            header?: never;
            path: {
                name: components["parameters"]["ProviderName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider balances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceHistoryResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAdapters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Adapter metadata listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdaptersResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAdapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Adapter metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdapterMetadata"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstancesResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceSpec"];
            };
        };
        responses: {
            /** @description Instance created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSpec"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSpec"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceSpec"];
            };
        };
        responses: {
            /** @description Instance updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSpec"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        id?: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance start response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceActionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    stopInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance stop response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceActionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listInstanceOrders: {
        parameters: {
            query?: {
                limit?: number;
                provider?: string;
                states?: string[];
            };
            header?: never;
            path: {
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderHistoryResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listInstanceExecutions: {
        parameters: {
            query?: {
                limit?: number;
                provider?: string;
                orderId?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionHistoryResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRiskLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Risk limits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Present when limits were updated in this response */
                        status?: string;
                        limits?: components["schemas"]["RiskConfig"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateRiskLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskConfig"];
            };
        };
        responses: {
            /** @description Updated risk limits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        limits?: components["schemas"]["RiskConfig"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Context backup payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextBackupPayload"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    restoreContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextBackupPayload"];
            };
        };
        responses: {
            /** @description Restore status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreContextResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listOutbox: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteOutbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxDeleteResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
