// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	ID         int64              `db:"id" json:"id"`
	ProviderID int64              `db:"provider_id" json:"provider_id"`
	Asset      string             `db:"asset" json:"asset"`
	Total      pgtype.Numeric     `db:"total" json:"total"`
	Available  pgtype.Numeric     `db:"available" json:"available"`
	SnapshotAt time.Time          `db:"snapshot_at" json:"snapshot_at"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EventsOutbox struct {
	ID            int64              `db:"id" json:"id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string             `db:"aggregate_id" json:"aggregate_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Payload       []byte             `db:"payload" json:"payload"`
	Headers       []byte             `db:"headers" json:"headers"`
	AvailableAt   pgtype.Timestamptz `db:"available_at" json:"available_at"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Attempts      int32              `db:"attempts" json:"attempts"`
	LastError     pgtype.Text        `db:"last_error" json:"last_error"`
	Delivered     bool               `db:"delivered" json:"delivered"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Execution struct {
	ID           int64              `db:"id" json:"id"`
	OrderID      pgtype.UUID        `db:"order_id" json:"order_id"`
	ProviderID   int64              `db:"provider_id" json:"provider_id"`
	ExecutionID  string             `db:"execution_id" json:"execution_id"`
	FillQuantity pgtype.Numeric     `db:"fill_quantity" json:"fill_quantity"`
	FillPrice    pgtype.Numeric     `db:"fill_price" json:"fill_price"`
	Fee          pgtype.Numeric     `db:"fee" json:"fee"`
	FeeAsset     pgtype.Text        `db:"fee_asset" json:"fee_asset"`
	Liquidity    pgtype.Text        `db:"liquidity" json:"liquidity"`
	TradedAt     pgtype.Timestamptz `db:"traded_at" json:"traded_at"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Order struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ProviderID         int64              `db:"provider_id" json:"provider_id"`
	StrategyInstanceID pgtype.UUID        `db:"strategy_instance_id" json:"strategy_instance_id"`
	ClientOrderID      string             `db:"client_order_id" json:"client_order_id"`
	Instrument         string             `db:"instrument" json:"instrument"`
	Side               string             `db:"side" json:"side"`
	OrderType          string             `db:"order_type" json:"order_type"`
	Quantity           pgtype.Numeric     `db:"quantity" json:"quantity"`
	Price              pgtype.Numeric     `db:"price" json:"price"`
	State              string             `db:"state" json:"state"`
	ExternalOrderRef   pgtype.Text        `db:"external_order_ref" json:"external_order_ref"`
	PlacedAt           pgtype.Timestamptz `db:"placed_at" json:"placed_at"`
	AcknowledgedAt     pgtype.Timestamptz `db:"acknowledged_at" json:"acknowledged_at"`
	CompletedAt        pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Provider struct {
	ID                int64              `db:"id" json:"id"`
	Alias             string             `db:"alias" json:"alias"`
	DisplayName       string             `db:"display_name" json:"display_name"`
	AdapterIdentifier string             `db:"adapter_identifier" json:"adapter_identifier"`
	Connection        []byte             `db:"connection" json:"connection"`
	Status            string             `db:"status" json:"status"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProviderRoute struct {
	ID         int64              `db:"id" json:"id"`
	ProviderID int64              `db:"provider_id" json:"provider_id"`
	Symbol     string             `db:"symbol" json:"symbol"`
	Route      []byte             `db:"route" json:"route"`
	Version    int32              `db:"version" json:"version"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StrategyInstance struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	StrategyIdentifier string             `db:"strategy_identifier" json:"strategy_identifier"`
	Tag                string             `db:"tag" json:"tag"`
	Status             string             `db:"status" json:"status"`
	ConfigHash         string             `db:"config_hash" json:"config_hash"`
	Description        string             `db:"description" json:"description"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	InstanceID         string             `db:"instance_id" json:"instance_id"`
}
