// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_routes.sql

package sqlc

import (
	"context"
)

const deleteProviderRoute = `-- name: DeleteProviderRoute :exec
DELETE FROM provider_routes
WHERE provider_id = $1::bigint AND symbol = $2::text
`

type DeleteProviderRouteParams struct {
	ProviderID int64  `db:"provider_id" json:"provider_id"`
	Symbol     string `db:"symbol" json:"symbol"`
}

func (q *Queries) DeleteProviderRoute(ctx context.Context, arg DeleteProviderRouteParams) error {
	_, err := q.db.Exec(ctx, deleteProviderRoute, arg.ProviderID, arg.Symbol)
	return err
}

const deleteRoutesByProvider = `-- name: DeleteRoutesByProvider :exec
DELETE FROM provider_routes
WHERE provider_id = $1::bigint
`

func (q *Queries) DeleteRoutesByProvider(ctx context.Context, providerID int64) error {
	_, err := q.db.Exec(ctx, deleteRoutesByProvider, providerID)
	return err
}

const listProviderRoutes = `-- name: ListProviderRoutes :many
SELECT id, provider_id, symbol, route, version, metadata, created_at, updated_at FROM provider_routes
WHERE provider_id = $1::bigint
ORDER BY symbol
`

func (q *Queries) ListProviderRoutes(ctx context.Context, providerID int64) ([]ProviderRoute, error) {
	rows, err := q.db.Query(ctx, listProviderRoutes, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderRoute
	for rows.Next() {
		var i ProviderRoute
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Symbol,
			&i.Route,
			&i.Version,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProviderRoute = `-- name: UpsertProviderRoute :one
INSERT INTO provider_routes (
    provider_id,
    symbol,
    route,
    version,
    metadata,
    updated_at
)
VALUES (
    $1::bigint,
    $2::text,
    COALESCE($3::jsonb, '{}'::jsonb),
    COALESCE($4::int, 1),
    COALESCE($5::jsonb, '{}'::jsonb),
    NOW()
)
ON CONFLICT (provider_id, symbol) DO
UPDATE SET
    route = EXCLUDED.route,
    version = EXCLUDED.version,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
RETURNING id, provider_id, symbol, route, version, metadata, created_at, updated_at
`

type UpsertProviderRouteParams struct {
	ProviderID int64  `db:"provider_id" json:"provider_id"`
	Symbol     string `db:"symbol" json:"symbol"`
	Route      []byte `db:"route" json:"route"`
	Version    int32  `db:"version" json:"version"`
	Metadata   []byte `db:"metadata" json:"metadata"`
}

func (q *Queries) UpsertProviderRoute(ctx context.Context, arg UpsertProviderRouteParams) (ProviderRoute, error) {
	row := q.db.QueryRow(ctx, upsertProviderRoute,
		arg.ProviderID,
		arg.Symbol,
		arg.Route,
		arg.Version,
		arg.Metadata,
	)
	var i ProviderRoute
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Symbol,
		&i.Route,
		&i.Version,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
